
application: byte-me-appengine
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /induviae_style\.css
  static_files: static/induviae_style.css
  upload: static/induviae_style\.css

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
- name: markupsafe
  version: latest
